server:
  port: 8082
spring:
  profiles:
    active: druidDtaSource

---
spring:
  datasource: #command 点击url,username等可以产看对应的properties文件
      url: jdbc:mysql://localhost:3306/testDB #提前创建好数据库testDB,否则会启动失败
      username: root
      password: 123123
      driver-class-name: com.mysql.cj.jdbc.Driver # com.mysql.jdbc.Driver is deprecated
  sql:
    init:
      schema-locations:
        - classpath:departmentDDL.sql #结合下面的initialization-mode=always会在应用启动的时候执行指定文件的中的DML sql
      data-locations:
        - classpath:departmentDML.sql #结合下面的initialization-mode=always会在应用启动的时候执行指定文件的中的DDL sql
      mode: always
  config:
    activate:
      on-profile: defaultDataSource


---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testDB
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #显式的指定druid数据源,将会覆盖默认的Hikari数据源，后面的参数需要显式的绑定到自定义的DruidConfig配置类中
    initialSize: 20
    maxActive: 30
    minIdle: 10


  sql:
    init:
      schema-locations:
        - classpath:departmentDDL.sql
        - classpath:departmentDML.sql
      mode: always
  config:
    activate:
      on-profile: druidDtaSource